name: ci-app
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
  steps:
    - uses: actions/setup-node@v3
    - run: make install
    - run: make build
    - run: make start
    - run: make test
    - run: make lint
